sonar.projectKey=notes_app
sonar.projectName=Notes App
sonar.sources=client/src,server/src
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.host.url=http://localhost:9000
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info